#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '2.3'
services:
  RTFNet:
    # Uncomment the next line to use a non-root user for all processes. You can also
    # simply use the "remoteUser" property in devcontainer.json if you just want VS Code
    # and its sub-processes (terminals, tasks, debugging) to execute as the user. On Linux,
    # you may need to update USER_UID and USER_GID in .devcontainer/Dockerfile to match your
    # user if not 1000. See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: vscode
    runtime: nvidia
    image: docker_image_rtfnet # The name of the docker image
    ports:
      - '1234:6006' 
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached # Do not change!
      # - /home/sun/somefolder/:/somefolder # folder_in_local_computer:folder_in_docker_container

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
    shm_size: 32g
    devices: 
      - /dev/nvidia0
      - /dev/nvidia1 # Please add or delete according to the number of your GPU cards

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    #entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
